### ISSUE TITLE
unit test: Find(id)

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#10]

**Comment by cgourdin** [comment]
Find is called as expected, but there is a problem, if i query Erocci on "/" 
ex : curl -v -X GET http://localhost:8080/ -H "accept: application/json"
Erocci give me a 404 because he call the "Find" method with an empty id. Should Erocci call find if the path = "/" ? Should Erocci give internal server informations instead for this particular query ?

**Comment by jeanparpaillon** [comment]
Mmmh, I prefer answering 404.
To be conform, GET '/' should return the collection of all entities of the server. I'm not sure this is useful for users (collections are made on purpose) and may quickly overload the server.

**Comment by cgourdin** [comment]
This is used on CloudDesigner with jocci connector. That's why i have forward this question. JOCCI connector use a default server address to connect the client, if a 404 is rendered, it cause an exception thrown.

**Comment by jeanparpaillon** [comment]
I would say this is a bug from jOCCI because the only mandatory url on an OCCI endpoint is '/-/'
Nothing in the spec prevents from answering 404
jOCCI should use this url for testing an endpoint.
Could you fill a bug on https://github.com/Misenko/jOCCI-core or https://github.com/Misenko/jOCCI-api ?

**Comment by cgourdin** [comment]
Ok, i will test with that url thanks. When i finish my tests with jOCCI, i'll fill bug on jOCCI github project.

**Comment by cgourdin** [comment]
I have done more investigations, i found that the connection between jOCCI and Erocci work, if i give to jOCCI an address like this : http://localhost:8080 . On the connection, jOCCI map to '/-/' and state that connection is ok. 
For listing an entities collection URIs, jOCCI request to the address "http://localhost:8080/" and Erocci call the method Find(id) instead of List(id, filters). 
On Erocci to list an entity collections, we need to query on "http://localhost:8080/collections/entity/", i conclude also that jOCCI is not compatible with Erocci.

**Comment by jeanparpaillon** [comment]
> I have done more investigations, i found that the connection between jOCCI and Erocci work, if i give 
> to jOCCI an address like this : http://localhost:8080 . On the connection, jOCCI map to '/-/' and state 
> that connection is ok.

Ok, fine

> For listing an entities collection URIs, jOCCI request to the address "http://localhost:8080/" and 
> Erocci call the method Find(id) instead of List(id, filters).

This is fine, as erocci calls `List` directly only when it is a bounded collection (see definition on HTTP specifiction).
Then, it is up to your backend to answer if "/" is an entity, an unbounded collection or... nothing.

> On Erocci to list an entity collections, we need to query on "http://localhost:8080/collections/entity/", 
> i conclude also that jOCCI is not compatible with Erocci.

I don't really understand what is your request and what is it expected. The question is: is it compliant with HTTP specification (see https://github.com/occiware/occi-wg)

**Comment by cgourdin** [comment]
I see now, if "id" parameter is set to "/" or empty, i return an unbounded collection and effectively Erocci call List method accordingly now.
Thanks you !
