### ISSUE TITLE
unit test: SaveMixin(id, entities)

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/erocci-dbus-java#8]

**Comment by cgourdin** [comment]
This method associate a list of entities with a mixin, replacing existing list if any previously given.
The method has been tested with my unit tests (without dbus connection) and has not been tested with Erocci connection, because i have no sample of curl query to access to this method. 
Could you provide me an example of curl query for this ?

**Comment by jeanparpaillon** [comment]
The method may be misnamed: it is called with a request like
PUT /collection/mixin

and set of full list of entities to be associated with the mixin

With text rendering, content is:
x-occi-location: /entity1, /entity2, /entity3 ...
